#include <iostream>
#include <vector>
#include "../inc/sequence_processing.h"


int main() {
    std::vector<std::string> threonine_amino_acids{"acu", "acc", "aca", "acg"};
    std::vector<std::string> lysine_amino_acids{"aaa", "aag"};
    std::vector<std::string> alanine_amino_acids{"gct", "gcc", "gca", "gcg"};
    std::vector<std::string> aspargine_amino_acids{"aat", "aac" };

    std::vector<int> positions_to_mutate{157, 202, 532, 733, 769, 796};

    std::string rna = "gcagacggcgctgagcgcggcggcggcgggagcggcgtcgagtgtctccgtgcgcccgtctgtggccaagcagccagcagcctagcagccagtcagcttgccgccggcggccaagcagccaaccatgctcaacttcggtgcctctctccagcagactgcggaggaaagaatggaaatgatttctgaaaggccaaaagagagtatgtattcctggaacaaaactgcagagaaaagtgattttgaagctgtagaagcacttatgtcaatgagctgcagttggaagtctgattttaagaaatacgttgaaaacagacctgttacaccagtatctgatttgtcagaggaagagaatctgcttccgggaacacctgattttcatacaatcccagcattttgtttgactccaccttacagtccttctgactttgaaccctctcaagtgtcaaatctgatggcaccagcgccatctactgtacacttcaagtcactctcagatactgccaaacctcacattgccgcacctttcaaagaggaagaaaagagcccagtatctgcccccaaactccccaaagctcaggcaacaagtgtgattcgtcatacagctgatgcccagctatgtaaccaccagacctgcccaatgaaagcagccagcatcctcaactatcagaacaattcttttagaagaagaacccacctaaatgttgaggctgcaagaaagaacataccatgtgccgctgtgtcaccaaacagatccaaatgtgagagaaacacagtggcagatgttgatgagaaagcaagtgctgcactttatgacttttctgtgccttcctcagagacggtcatctgcaggtctcagccagcccctgtgtccccacaacagaagtcagtgttggtctctccacctgcagtatctgcagggggagtgccacctatgccggtcatctgccagatggttccccttcctgccaacaaccctgttgtgacaacagtcgttcccagcactcctcccagccagccaccagccgtttgcccccctgttgtgttcatgggcacacaagtccccaaaggcgctgtcatgtttgtggtaccccagcccgttgtgcagagttcaaagcctccggtggtgagcccgaatggcaccagactctctcccattgcccctgctcctgggttttccccttcagcagcaaaagtcactcctcagattgattcatcaaggataaggagtcacatctgtagccacccaggatgtggcaagacatactttaaaagttcccatctgaaggcccacacgaggacgcacacaggagaaaagcctttcagctgtagctggaaaggttgtgaaaggaggtttgcccgttctgatgaactgtccagacacaggcgaacccacacgggtgagaagaaatttgcgtgccccatgtgtgaccggcggttcatgaggagtgaccatttgaccaagcatgcccggcgccatctatcagccaagaagctaccaaactggcagatggaagtgagcaagctaaatgacattgctctacctccaacccctgctcccacacagtgacagaccggaaagtgaagagtcagaactaactttggtctcagcgggagccagtggtgatgtaaaaatgcttccactgcaagtctgtggccccacaacgtgggcttaaagcagaagccccacagcctggcacgaaggccccgcctgggttaggtgactaaaagggcttcggccacaggcaggtcacagaaaggcaggtttcatttcttatcacataagagagatgagaaagcttttattcctttgaatattttttgaaggtttcagatgaggtcaacacaggtagcacagattttgaatctgtgtgcatatttgttactttacttttgctgtttatacttgagaccaacttttcaatgtgattcttctaaagcactggtttcaagaatatggaggctggaaggaaataaacattacggtacagacatggagatgtaaaatgagtttgtattattacaaatattgtcatctttttctagagttatcttctttattattcctagtctttccagtcaacatcgtggatgtagtgattaaatatatctagaactatcatttttacactattgtgaatatttggaattgaacgactgtatattgctaagagggcccaaagaattggaatcctccttaatttaattgctttgaagcatagctacaatttgtttttgcatttttgttttgaaagtttaacaaatgactgtatctaggcatttcattatgctttgaactttagtttgcctgcagtttcttgtgtagatttgaaaattgtataccaatgtgttttctgtagactctaagatacactgcactttgtttagaaaaaaaactgaagatgaaatatatattgtaaagaagggatattaagaatcttagataacttcttgaaaaagatggcttatgtcatcagtaaagtacctttatgttatgaggatataatgtgtgctttattgaattagaaaattagtgaccattattcacaggtggacaaatgttgatgttgtcctgttaatttataggcgttttttggggatgtggaggtagttgggtagaaaaattattagaacattcacttttgttaacagtatttctcttttattctgttatatagtggatgatatacacagtggcaaaacaaaagtacattgcttaaaatatatagtgaaaaatgtcactatatcttcccatttaacattgtttttgtatattgggtgtagatttctgacatcaaaacttggacccttggaaaacaaaagttttaattaaaaaaaatccttgtgacttacaatttgcacaatatttcttttgttgtactttatatcttgtttacaataaagaattccctttggta";
    std::string mutated_rna = amino_acid_replacement(rna,threonine_amino_acids[0],positions_to_mutate[0]);
    std::cout << mutated_rna << std::endl;
    return 0;
}
